# Documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - bash -c "test -f {{.Env.UI_FILE}} || make build-web UI_FILE={{.Env.UI_FILE}}"
dist: .tmp/dist
builds:
  - binary: client-application
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
      - ppc64
      - ppc64le
    goarm:
      - "7"
    main: ./cmd
    ldflags:
      - -s -w -X main.ReleaseURL={{.ReleaseURL}}
      - -s -w -X main.CommitDate={{.CommitDate}}
      - -s -w -X main.CommitHash={{.ShortCommit}}
      - -s -w -X main.BuildDate={{.Date}}
      - -s -w -X main.Version={{.Version}}
      - -s -w -X main.UISeparator={{.Env.UI_SEPARATOR}}
      - -extldflags '-static'
    hooks:
      post:
        - bash -c "test {{.Os}} == "windows" || test {{.Os}} == "darwin" || upx --best --lzma {{.Path}}"
        - make inject-web CLIENT_APPLICATION_BINARY_PATH={{.Path}} UI_SEPARATOR={{.Env.UI_SEPARATOR}} UI_FILE={{.Env.UI_FILE}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{.Os}}{{ end }}_{{ if eq .Arch "386"}}i{{ end }}{{ .Arch }}'
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
