log:
  level: info
  encoding: json
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  http:
    enabled: true
    address: 0.0.0.0:8080
    tls:
      enabled: false
      caPool: /certs/ca.pem
      keyFile: /certs/key.pem
      certFile: /certs/crt.pem
      clientCertificateRequired: true
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Accept
        - Accept-Language
        - Accept-Encoding
        - Content-Type
        - Content-Language
        - Content-Length
        - Origin
        - X-CSRF-Token
        - Authorization
      allowedMethods:
        - GET
        - PATCH
        - HEAD
        - POST
        - PUT
        - OPTIONS
        - DELETE
      allowCredentials: false
  grpc:
    enabled: true
    address: 0.0.0.0:8081
    enforcementPolicy:
      minTime: 5s
      permitWithoutStream: true
    keepAlive:
      maxConnectionIdle: 0s
      maxConnectionAge: 0s
      maxConnectionAgeGrace: 0s
      time: 0s
      timeout: 0s
    tls:
      enabled: false
      caPool: /certs/ca.pem
      keyFile: /certs/key.pem
      certFile: /certs/crt.pem
      clientCertificateRequired: true