log:
  level: info
  encoding: json
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  http:
    address: localhost:40050
    tls:
      enabled: false
      caPool: /certs/ca.pem
      keyFile: /certs/key.pem
      certFile: /certs/crt.pem
      clientCertificateRequired: true