log:
  level: info
  encoding: console
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  http:
    enabled: true
    address: 0.0.0.0:8080
    readTimeout: 8s
    readHeaderTimeout: 4s
    writeTimeout: 16s
    idleTimeout: 30s
    tls:
      enabled: false
      caPool: /certs/ca.pem
      keyFile: /certs/key.pem
      certFile: /certs/crt.pem
      clientCertificateRequired: true
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Accept
        - Accept-Language
        - Accept-Encoding
        - Content-Type
        - Content-Language
        - Content-Length
        - Origin
        - X-CSRF-Token
        - Authorization
      allowedMethods:
        - GET
        - PATCH
        - HEAD
        - POST
        - PUT
        - OPTIONS
        - DELETE
      allowCredentials: false
    ui:
      enabled: false
      directory: ""
  grpc:
    enabled: true
    address: 0.0.0.0:8081
    enforcementPolicy:
      minTime: 5s
      permitWithoutStream: false
    keepAlive:
      maxConnectionIdle: 0s
      maxConnectionAge: 0s
      maxConnectionAgeGrace: 0s
      time: 0s
      timeout: 0s
    tls:
      enabled: false
      caPool: /certs/ca.pem
      keyFile: /certs/key.pem
      certFile: /certs/crt.pem
      clientCertificateRequired: true
clients:
  device:
    coap:
      maxMessageSize: 262144
      inactivityMonitor:
        timeout: 10s
      blockwiseTransfer:
        enabled: true
        blockSize: "1024"
      ownershipTransfer:
        methods:
          - justWorks
        manufacturerCertificate:
          tls:
            caPool: /certs/mfg_ca.pem
            keyFile: /certs/mfg_key.pem
            certFile: /certs/mfg_crt.pem
      tls:
        authentication: preSharedKey
        preSharedKey:
          subjectUuid: 57b3fae9-adf5-4e34-90ea-e77784407103
          keyUuid: 46178d21-d480-4e95-9bd3-6c9eefa8d9d8
