@startuml Sequence
skinparam backgroundColor transparent
hide footbox

box "D2D Client"
participant C as "Web App"
participant S as "Service"
end box

box "plgd hub"
participant CA as "Certificate Authority"
end box

alt GetConfiguration.device_authentication_mode == X509 && remote_provisioning.mode == USER_AGENT
  C -> S++: Own device
  activate C
  S -> C: Identity certificate challenge with identity CSR and state
  C -> CA ++: Sign identity CSR
  return Identity Certificate
  C -> S: Finish own device with state and identity certificate
  return
  deactivate S
  deactivate C
else
  C -> S ++: Own device
  return
end
@enduml
