// ************************************************************************
// Copyright (C) 2022 plgd.dev, s.r.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: github.com/plgd-dev/client-application/pb/get_identity_csr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JWT token must be used for extraction owner id.
type GetIdentityCSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIdentityCSRRequest) Reset() {
	*x = GetIdentityCSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityCSRRequest) ProtoMessage() {}

func (x *GetIdentityCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityCSRRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityCSRRequest) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescGZIP(), []int{0}
}

type GetIdentityCSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertificateSigningRequest []byte `protobuf:"bytes,1,opt,name=certificate_signing_request,json=certificateSigningRequest,proto3" json:"certificate_signing_request,omitempty"` // in PEM format
	State                     []byte `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                                                                            // for pairing GetIdentityCSR and UpdateIdentityCertificate
}

func (x *GetIdentityCSRResponse) Reset() {
	*x = GetIdentityCSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityCSRResponse) ProtoMessage() {}

func (x *GetIdentityCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityCSRResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityCSRResponse) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdentityCSRResponse) GetCertificateSigningRequest() []byte {
	if x != nil {
		return x.CertificateSigningRequest
	}
	return nil
}

func (x *GetIdentityCSRResponse) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

var File_github_com_plgd_dev_client_application_pb_get_identity_csr_proto protoreflect.FileDescriptor

var file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDesc = []byte{
	0x0a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67,
	0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x73, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x22, 0x17,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x53, 0x52,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x1b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x5f, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x19, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67, 0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescOnce sync.Once
	file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescData = file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDesc
)

func file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescGZIP() []byte {
	file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescOnce.Do(func() {
		file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescData)
	})
	return file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDescData
}

var file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_goTypes = []interface{}{
	(*GetIdentityCSRRequest)(nil),  // 0: service.pb.GetIdentityCSRRequest
	(*GetIdentityCSRResponse)(nil), // 1: service.pb.GetIdentityCSRResponse
}
var file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_init() }
func file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_init() {
	if File_github_com_plgd_dev_client_application_pb_get_identity_csr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentityCSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentityCSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_goTypes,
		DependencyIndexes: file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_depIdxs,
		MessageInfos:      file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_msgTypes,
	}.Build()
	File_github_com_plgd_dev_client_application_pb_get_identity_csr_proto = out.File
	file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_rawDesc = nil
	file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_goTypes = nil
	file_github_com_plgd_dev_client_application_pb_get_identity_csr_proto_depIdxs = nil
}
