// ************************************************************************
// Copyright (C) 2022 plgd.dev, s.r.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.3
// source: github.com/plgd-dev/client-application/pb/get_devices.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDevicesRequest_OwnershipStatusFilter int32

const (
	// get only unowned devices
	GetDevicesRequest_UNOWNED GetDevicesRequest_OwnershipStatusFilter = 0
	// get only owned devices
	GetDevicesRequest_OWNED GetDevicesRequest_OwnershipStatusFilter = 1
)

// Enum value maps for GetDevicesRequest_OwnershipStatusFilter.
var (
	GetDevicesRequest_OwnershipStatusFilter_name = map[int32]string{
		0: "UNOWNED",
		1: "OWNED",
	}
	GetDevicesRequest_OwnershipStatusFilter_value = map[string]int32{
		"UNOWNED": 0,
		"OWNED":   1,
	}
)

func (x GetDevicesRequest_OwnershipStatusFilter) Enum() *GetDevicesRequest_OwnershipStatusFilter {
	p := new(GetDevicesRequest_OwnershipStatusFilter)
	*p = x
	return p
}

func (x GetDevicesRequest_OwnershipStatusFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetDevicesRequest_OwnershipStatusFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_plgd_dev_client_application_pb_get_devices_proto_enumTypes[0].Descriptor()
}

func (GetDevicesRequest_OwnershipStatusFilter) Type() protoreflect.EnumType {
	return &file_github_com_plgd_dev_client_application_pb_get_devices_proto_enumTypes[0]
}

func (x GetDevicesRequest_OwnershipStatusFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetDevicesRequest_OwnershipStatusFilter.Descriptor instead.
func (GetDevicesRequest_OwnershipStatusFilter) EnumDescriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescGZIP(), []int{0, 0}
}

type GetDevicesRequest_UseMulticast int32

const (
	GetDevicesRequest_IPV4 GetDevicesRequest_UseMulticast = 0
	GetDevicesRequest_IPV6 GetDevicesRequest_UseMulticast = 1
)

// Enum value maps for GetDevicesRequest_UseMulticast.
var (
	GetDevicesRequest_UseMulticast_name = map[int32]string{
		0: "IPV4",
		1: "IPV6",
	}
	GetDevicesRequest_UseMulticast_value = map[string]int32{
		"IPV4": 0,
		"IPV6": 1,
	}
)

func (x GetDevicesRequest_UseMulticast) Enum() *GetDevicesRequest_UseMulticast {
	p := new(GetDevicesRequest_UseMulticast)
	*p = x
	return p
}

func (x GetDevicesRequest_UseMulticast) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetDevicesRequest_UseMulticast) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_plgd_dev_client_application_pb_get_devices_proto_enumTypes[1].Descriptor()
}

func (GetDevicesRequest_UseMulticast) Type() protoreflect.EnumType {
	return &file_github_com_plgd_dev_client_application_pb_get_devices_proto_enumTypes[1]
}

func (x GetDevicesRequest_UseMulticast) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetDevicesRequest_UseMulticast.Descriptor instead.
func (GetDevicesRequest_UseMulticast) EnumDescriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescGZIP(), []int{0, 1}
}

// Returns a list of devices. The list is sorted by device id. If use_cache, use_multicast, use_endpoints are not set, then it will set use_multicast with [IPV4,IPV6].
type GetDevicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Devices are taken from the cache. Default: false.
	UseCache bool `protobuf:"varint,1,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`
	// Filter by multicast IP address version. Default: [] - multicast is disabled. If it is set, the new devices will be added to cache.
	UseMulticast []GetDevicesRequest_UseMulticast `protobuf:"varint,2,rep,packed,name=use_multicast,json=useMulticast,proto3,enum=service.pb.GetDevicesRequest_UseMulticast" json:"use_multicast,omitempty"`
	// Returns devices via endpoints. Default: [] - filter is disabled. New devices will be added to cache. Not reachable devices will be not in response.
	// Endpoint can be in format:
	// - <host>:<port> is interpreted as coap://<host>:<port>
	// - <host> is interpreted as coap://<host>:5683
	UseEndpoints []string `protobuf:"bytes,3,rep,name=use_endpoints,json=useEndpoints,proto3" json:"use_endpoints,omitempty"`
	// How long to wait for the devices responses for responses in nanoseconds. Default: 0 - means 2sec.
	Timeout int64 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Filter by ownership status. Default: [UNOWNED,OWNED].
	OwnershipStatusFilter []GetDevicesRequest_OwnershipStatusFilter `protobuf:"varint,5,rep,packed,name=ownership_status_filter,json=ownershipStatusFilter,proto3,enum=service.pb.GetDevicesRequest_OwnershipStatusFilter" json:"ownership_status_filter,omitempty"`
	// Filter by device resource type of oic/d. Default: [] - filter is disabled.
	TypeFilter []string `protobuf:"bytes,6,rep,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
}

func (x *GetDevicesRequest) Reset() {
	*x = GetDevicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_devices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesRequest) ProtoMessage() {}

func (x *GetDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_devices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescGZIP(), []int{0}
}

func (x *GetDevicesRequest) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

func (x *GetDevicesRequest) GetUseMulticast() []GetDevicesRequest_UseMulticast {
	if x != nil {
		return x.UseMulticast
	}
	return nil
}

func (x *GetDevicesRequest) GetUseEndpoints() []string {
	if x != nil {
		return x.UseEndpoints
	}
	return nil
}

func (x *GetDevicesRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *GetDevicesRequest) GetOwnershipStatusFilter() []GetDevicesRequest_OwnershipStatusFilter {
	if x != nil {
		return x.OwnershipStatusFilter
	}
	return nil
}

func (x *GetDevicesRequest) GetTypeFilter() []string {
	if x != nil {
		return x.TypeFilter
	}
	return nil
}

var File_github_com_plgd_dev_client_application_pb_get_devices_proto protoreflect.FileDescriptor

var file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67,
	0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x65, 0x74, 0x5f,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x22, 0xa3, 0x03, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x75, 0x73, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x4f, 0x0a, 0x0d,
	0x75, 0x73, 0x65, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x63, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x63, 0x61, 0x73, 0x74, 0x52,
	0x0c, 0x75, 0x73, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x63, 0x61, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x75, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x6b, 0x0a, 0x17,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x33, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x15, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x15, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4f, 0x57, 0x4e, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x4f, 0x57, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x22, 0x22, 0x0a, 0x0c, 0x55,
	0x73, 0x65, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x63, 0x61, 0x73, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x49,
	0x50, 0x56, 0x34, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x50, 0x56, 0x36, 0x10, 0x01, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c,
	0x67, 0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescOnce sync.Once
	file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescData = file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDesc
)

func file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescGZIP() []byte {
	file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescOnce.Do(func() {
		file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescData)
	})
	return file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDescData
}

var file_github_com_plgd_dev_client_application_pb_get_devices_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_plgd_dev_client_application_pb_get_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_plgd_dev_client_application_pb_get_devices_proto_goTypes = []interface{}{
	(GetDevicesRequest_OwnershipStatusFilter)(0), // 0: service.pb.GetDevicesRequest.OwnershipStatusFilter
	(GetDevicesRequest_UseMulticast)(0),          // 1: service.pb.GetDevicesRequest.UseMulticast
	(*GetDevicesRequest)(nil),                    // 2: service.pb.GetDevicesRequest
}
var file_github_com_plgd_dev_client_application_pb_get_devices_proto_depIdxs = []int32{
	1, // 0: service.pb.GetDevicesRequest.use_multicast:type_name -> service.pb.GetDevicesRequest.UseMulticast
	0, // 1: service.pb.GetDevicesRequest.ownership_status_filter:type_name -> service.pb.GetDevicesRequest.OwnershipStatusFilter
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_plgd_dev_client_application_pb_get_devices_proto_init() }
func file_github_com_plgd_dev_client_application_pb_get_devices_proto_init() {
	if File_github_com_plgd_dev_client_application_pb_get_devices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_plgd_dev_client_application_pb_get_devices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDevicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_plgd_dev_client_application_pb_get_devices_proto_goTypes,
		DependencyIndexes: file_github_com_plgd_dev_client_application_pb_get_devices_proto_depIdxs,
		EnumInfos:         file_github_com_plgd_dev_client_application_pb_get_devices_proto_enumTypes,
		MessageInfos:      file_github_com_plgd_dev_client_application_pb_get_devices_proto_msgTypes,
	}.Build()
	File_github_com_plgd_dev_client_application_pb_get_devices_proto = out.File
	file_github_com_plgd_dev_client_application_pb_get_devices_proto_rawDesc = nil
	file_github_com_plgd_dev_client_application_pb_get_devices_proto_goTypes = nil
	file_github_com_plgd_dev_client_application_pb_get_devices_proto_depIdxs = nil
}
