// ************************************************************************
// Copyright (C) 2022 plgd.dev, s.r.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: github.com/plgd-dev/client-application/pb/get_configuration.proto

package pb

import (
	pb "github.com/plgd-dev/hub/v2/grpc-gateway/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteProvisioning_Mode int32

const (
	RemoteProvisioning_MODE_NONE  RemoteProvisioning_Mode = 0
	RemoteProvisioning_USER_AGENT RemoteProvisioning_Mode = 1
)

// Enum value maps for RemoteProvisioning_Mode.
var (
	RemoteProvisioning_Mode_name = map[int32]string{
		0: "MODE_NONE",
		1: "USER_AGENT",
	}
	RemoteProvisioning_Mode_value = map[string]int32{
		"MODE_NONE":  0,
		"USER_AGENT": 1,
	}
)

func (x RemoteProvisioning_Mode) Enum() *RemoteProvisioning_Mode {
	p := new(RemoteProvisioning_Mode)
	*p = x
	return p
}

func (x RemoteProvisioning_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteProvisioning_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_enumTypes[0].Descriptor()
}

func (RemoteProvisioning_Mode) Type() protoreflect.EnumType {
	return &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_enumTypes[0]
}

func (x RemoteProvisioning_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteProvisioning_Mode.Descriptor instead.
func (RemoteProvisioning_Mode) EnumDescriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{2, 0}
}

type GetConfigurationResponse_DeviceAuthenticationMode int32

const (
	GetConfigurationResponse_PRE_SHARED_KEY GetConfigurationResponse_DeviceAuthenticationMode = 0
	GetConfigurationResponse_X509           GetConfigurationResponse_DeviceAuthenticationMode = 1
	GetConfigurationResponse_UNINITIALIZED  GetConfigurationResponse_DeviceAuthenticationMode = 2
)

// Enum value maps for GetConfigurationResponse_DeviceAuthenticationMode.
var (
	GetConfigurationResponse_DeviceAuthenticationMode_name = map[int32]string{
		0: "PRE_SHARED_KEY",
		1: "X509",
		2: "UNINITIALIZED",
	}
	GetConfigurationResponse_DeviceAuthenticationMode_value = map[string]int32{
		"PRE_SHARED_KEY": 0,
		"X509":           1,
		"UNINITIALIZED":  2,
	}
)

func (x GetConfigurationResponse_DeviceAuthenticationMode) Enum() *GetConfigurationResponse_DeviceAuthenticationMode {
	p := new(GetConfigurationResponse_DeviceAuthenticationMode)
	*p = x
	return p
}

func (x GetConfigurationResponse_DeviceAuthenticationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetConfigurationResponse_DeviceAuthenticationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_enumTypes[1].Descriptor()
}

func (GetConfigurationResponse_DeviceAuthenticationMode) Type() protoreflect.EnumType {
	return &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_enumTypes[1]
}

func (x GetConfigurationResponse_DeviceAuthenticationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetConfigurationResponse_DeviceAuthenticationMode.Descriptor instead.
func (GetConfigurationResponse_DeviceAuthenticationMode) EnumDescriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{5, 0}
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{0}
}

type UserAgent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in nanoseconds
	CsrChallengeStateExpiration int64 `protobuf:"varint,1,opt,name=csr_challenge_state_expiration,json=csrChallengeStateExpiration,proto3" json:"csr_challenge_state_expiration,omitempty" yaml:"csrChallengeStateExpiration"` // @gotags: yaml:"csrChallengeStateExpiration"
}

func (x *UserAgent) Reset() {
	*x = UserAgent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAgent) ProtoMessage() {}

func (x *UserAgent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAgent.ProtoReflect.Descriptor instead.
func (*UserAgent) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *UserAgent) GetCsrChallengeStateExpiration() int64 {
	if x != nil {
		return x.CsrChallengeStateExpiration
	}
	return 0
}

type RemoteProvisioning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentTime   int64  `protobuf:"varint,1,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty" yaml:"-"`        // @gotags: yaml:"-"
	JwtOwnerClaim string `protobuf:"bytes,2,opt,name=jwt_owner_claim,json=jwtOwnerClaim,proto3" json:"jwt_owner_claim,omitempty" yaml:"ownerClaim"` // @gotags: yaml:"ownerClaim"
	// Hub ID
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty" yaml:"hubID"` // @gotags: yaml:"hubID"
	// coap-gateway in format coaps+tcp://host:port
	CoapGateway string `protobuf:"bytes,5,opt,name=coap_gateway,json=coapGateway,proto3" json:"coap_gateway,omitempty" yaml:"coapGateway"` // @gotags: yaml:"coapGateway"
	// certificate_authorities in format PEM - can contain multiple certificates
	CertificateAuthorities string `protobuf:"bytes,6,opt,name=certificate_authorities,json=certificateAuthorities,proto3" json:"certificate_authorities,omitempty" yaml:"-"` // @gotags: yaml:"-"
	// authority in format https://host:port
	Authority string `protobuf:"bytes,7,opt,name=authority,proto3" json:"authority,omitempty" yaml:"authority"` // @gotags: yaml:"authority"
	// certificate_authority in format https://host:port
	CertificateAuthority string `protobuf:"bytes,9,opt,name=certificate_authority,json=certificateAuthority,proto3" json:"certificate_authority,omitempty" yaml:"certificateAuthority"` // @gotags: yaml:"certificateAuthority"
	// http-gateway in format https://host:port
	// string http_gateway_address = 10; // @gotags: yaml:"-"
	WebOauthClient    *pb.OAuthClient         `protobuf:"bytes,11,opt,name=web_oauth_client,json=webOauthClient,proto3" json:"web_oauth_client,omitempty" yaml:"webOAuthClient"`          // @gotags: yaml:"webOAuthClient"
	DeviceOauthClient *pb.OAuthClient         `protobuf:"bytes,12,opt,name=device_oauth_client,json=deviceOauthClient,proto3" json:"device_oauth_client,omitempty" yaml:"deviceOAuthClient"` // @gotags: yaml:"deviceOAuthClient"
	M2MOauthClient    *pb.OAuthClient         `protobuf:"bytes,13,opt,name=m2m_oauth_client,json=m2mOauthClient,proto3" json:"m2m_oauth_client,omitempty" yaml:"m2mOAuthClient"`          // @gotags: yaml:"m2mOAuthClient"
	Mode              RemoteProvisioning_Mode `protobuf:"varint,100,opt,name=mode,proto3,enum=service.pb.RemoteProvisioning_Mode" json:"mode,omitempty" yaml:"mode"`            // @gotags: yaml:"mode"
	UserAgent         *UserAgent              `protobuf:"bytes,101,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty" yaml:"userAgent"`                          // @gotags: yaml:"userAgent"
	CaPool            []string                `protobuf:"bytes,102,rep,name=ca_pool,json=caPool,proto3" json:"ca_pool,omitempty" yaml:"caPool"`                                   // @gotags: yaml:"caPool"
}

func (x *RemoteProvisioning) Reset() {
	*x = RemoteProvisioning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteProvisioning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteProvisioning) ProtoMessage() {}

func (x *RemoteProvisioning) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteProvisioning.ProtoReflect.Descriptor instead.
func (*RemoteProvisioning) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *RemoteProvisioning) GetCurrentTime() int64 {
	if x != nil {
		return x.CurrentTime
	}
	return 0
}

func (x *RemoteProvisioning) GetJwtOwnerClaim() string {
	if x != nil {
		return x.JwtOwnerClaim
	}
	return ""
}

func (x *RemoteProvisioning) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoteProvisioning) GetCoapGateway() string {
	if x != nil {
		return x.CoapGateway
	}
	return ""
}

func (x *RemoteProvisioning) GetCertificateAuthorities() string {
	if x != nil {
		return x.CertificateAuthorities
	}
	return ""
}

func (x *RemoteProvisioning) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *RemoteProvisioning) GetCertificateAuthority() string {
	if x != nil {
		return x.CertificateAuthority
	}
	return ""
}

func (x *RemoteProvisioning) GetWebOauthClient() *pb.OAuthClient {
	if x != nil {
		return x.WebOauthClient
	}
	return nil
}

func (x *RemoteProvisioning) GetDeviceOauthClient() *pb.OAuthClient {
	if x != nil {
		return x.DeviceOauthClient
	}
	return nil
}

func (x *RemoteProvisioning) GetM2MOauthClient() *pb.OAuthClient {
	if x != nil {
		return x.M2MOauthClient
	}
	return nil
}

func (x *RemoteProvisioning) GetMode() RemoteProvisioning_Mode {
	if x != nil {
		return x.Mode
	}
	return RemoteProvisioning_MODE_NONE
}

func (x *RemoteProvisioning) GetUserAgent() *UserAgent {
	if x != nil {
		return x.UserAgent
	}
	return nil
}

func (x *RemoteProvisioning) GetCaPool() []string {
	if x != nil {
		return x.CaPool
	}
	return nil
}

type BuildInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// version of the service
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// build date of the service
	BuildDate string `protobuf:"bytes,2,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	// commit hash of the service
	CommitHash string `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	// commit date of the service
	CommitDate string `protobuf:"bytes,4,opt,name=commit_date,json=commitDate,proto3" json:"commit_date,omitempty"`
	// release url of the service
	ReleaseUrl string `protobuf:"bytes,5,opt,name=release_url,json=releaseUrl,proto3" json:"release_url,omitempty"`
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *BuildInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *BuildInfo) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *BuildInfo) GetCommitDate() string {
	if x != nil {
		return x.CommitDate
	}
	return ""
}

func (x *BuildInfo) GetReleaseUrl() string {
	if x != nil {
		return x.ReleaseUrl
	}
	return ""
}

// UI configuration
type UIConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultDiscoveryTimeout int64 `protobuf:"varint,100,opt,name=default_discovery_timeout,json=defaultDiscoveryTimeout,proto3" json:"default_discovery_timeout,omitempty"` // default discovery timeout in nanoseconds
}

func (x *UIConfiguration) Reset() {
	*x = UIConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UIConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIConfiguration) ProtoMessage() {}

func (x *UIConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIConfiguration.ProtoReflect.Descriptor instead.
func (*UIConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *UIConfiguration) GetDefaultDiscoveryTimeout() int64 {
	if x != nil {
		return x.DefaultDiscoveryTimeout
	}
	return 0
}

type GetConfigurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                         // deprecated, use build_info.version
	BuildDate  string `protobuf:"bytes,2,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`    // deprecated, use build_info.build_date
	CommitHash string `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"` // deprecated, use build_info.commit_hash
	CommitDate string `protobuf:"bytes,4,opt,name=commit_date,json=commitDate,proto3" json:"commit_date,omitempty"` // deprecated, use build_info.commit_date
	ReleaseUrl string `protobuf:"bytes,5,opt,name=release_url,json=releaseUrl,proto3" json:"release_url,omitempty"` // deprecated, use build_info.release_url
	// user don't need to call initialize endpoint
	IsInitialized            bool                                              `protobuf:"varint,6,opt,name=is_initialized,json=isInitialized,proto3" json:"is_initialized,omitempty"`
	DeviceAuthenticationMode GetConfigurationResponse_DeviceAuthenticationMode `protobuf:"varint,7,opt,name=device_authentication_mode,json=deviceAuthenticationMode,proto3,enum=service.pb.GetConfigurationResponse_DeviceAuthenticationMode" json:"device_authentication_mode,omitempty"`
	RemoteProvisioning       *RemoteProvisioning                               `protobuf:"bytes,8,opt,name=remote_provisioning,json=remoteProvisioning,proto3" json:"remote_provisioning,omitempty"`
	Owner                    string                                            `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	BuildInfo                *BuildInfo                                        `protobuf:"bytes,10,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	Ui                       *UIConfiguration                                  `protobuf:"bytes,11,opt,name=ui,proto3" json:"ui,omitempty"`
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *GetConfigurationResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetConfigurationResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetConfigurationResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *GetConfigurationResponse) GetCommitDate() string {
	if x != nil {
		return x.CommitDate
	}
	return ""
}

func (x *GetConfigurationResponse) GetReleaseUrl() string {
	if x != nil {
		return x.ReleaseUrl
	}
	return ""
}

func (x *GetConfigurationResponse) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

func (x *GetConfigurationResponse) GetDeviceAuthenticationMode() GetConfigurationResponse_DeviceAuthenticationMode {
	if x != nil {
		return x.DeviceAuthenticationMode
	}
	return GetConfigurationResponse_PRE_SHARED_KEY
}

func (x *GetConfigurationResponse) GetRemoteProvisioning() *RemoteProvisioning {
	if x != nil {
		return x.RemoteProvisioning
	}
	return nil
}

func (x *GetConfigurationResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetConfigurationResponse) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *GetConfigurationResponse) GetUi() *UIConfiguration {
	if x != nil {
		return x.Ui
	}
	return nil
}

var File_github_com_plgd_dev_client_application_pb_get_configuration_proto protoreflect.FileDescriptor

var file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDesc = []byte{
	0x0a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67,
	0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x65, 0x74, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x1a,
	0x26, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x62,
	0x2f, 0x68, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x50, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x43, 0x0a, 0x1e, 0x63, 0x73, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1b, 0x63, 0x73, 0x72, 0x43, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xba, 0x05, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0f, 0x6a, 0x77, 0x74, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6a, 0x77, 0x74, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x61, 0x70, 0x5f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x61, 0x70, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x37, 0x0a, 0x17, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x12, 0x33, 0x0a, 0x15, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x14, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x10, 0x77, 0x65, 0x62, 0x5f, 0x6f, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x62,
	0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x0e, 0x77, 0x65,
	0x62, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x13,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x61,
	0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x10, 0x6d, 0x32, 0x6d,
	0x5f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x0e, 0x6d, 0x32, 0x6d, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x37, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x61, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x66, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x61, 0x50, 0x6f, 0x6f, 0x6c, 0x22, 0x25, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x4a,
	0x04, 0x08, 0x03, 0x10, 0x04, 0x4a, 0x04, 0x08, 0x08, 0x10, 0x09, 0x4a, 0x04, 0x08, 0x0a, 0x10,
	0x0b, 0x22, 0xa7, 0x01, 0x0a, 0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x4d, 0x0a, 0x0f, 0x55,
	0x49, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a,
	0x0a, 0x19, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x64, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x17, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0xf1, 0x04, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x69, 0x73, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x7b, 0x0a, 0x1a, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x18, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x4f, 0x0a, 0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x69, 0x6e, 0x67, 0x52, 0x12, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x34,
	0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x02, 0x75, 0x69, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x49,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x75,
	0x69, 0x22, 0x4b, 0x0a, 0x18, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x0e, 0x50, 0x52, 0x45, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x45, 0x44, 0x5f, 0x4b, 0x45, 0x59, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x58, 0x35, 0x30, 0x39, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x55,
	0x4e, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x02, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67,
	0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescOnce sync.Once
	file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescData = file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDesc
)

func file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescGZIP() []byte {
	file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescOnce.Do(func() {
		file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescData)
	})
	return file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDescData
}

var file_github_com_plgd_dev_client_application_pb_get_configuration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_plgd_dev_client_application_pb_get_configuration_proto_goTypes = []any{
	(RemoteProvisioning_Mode)(0),                           // 0: service.pb.RemoteProvisioning.Mode
	(GetConfigurationResponse_DeviceAuthenticationMode)(0), // 1: service.pb.GetConfigurationResponse.DeviceAuthenticationMode
	(*GetConfigurationRequest)(nil),                        // 2: service.pb.GetConfigurationRequest
	(*UserAgent)(nil),                                      // 3: service.pb.UserAgent
	(*RemoteProvisioning)(nil),                             // 4: service.pb.RemoteProvisioning
	(*BuildInfo)(nil),                                      // 5: service.pb.BuildInfo
	(*UIConfiguration)(nil),                                // 6: service.pb.UIConfiguration
	(*GetConfigurationResponse)(nil),                       // 7: service.pb.GetConfigurationResponse
	(*pb.OAuthClient)(nil),                                 // 8: grpcgateway.pb.OAuthClient
}
var file_github_com_plgd_dev_client_application_pb_get_configuration_proto_depIdxs = []int32{
	8, // 0: service.pb.RemoteProvisioning.web_oauth_client:type_name -> grpcgateway.pb.OAuthClient
	8, // 1: service.pb.RemoteProvisioning.device_oauth_client:type_name -> grpcgateway.pb.OAuthClient
	8, // 2: service.pb.RemoteProvisioning.m2m_oauth_client:type_name -> grpcgateway.pb.OAuthClient
	0, // 3: service.pb.RemoteProvisioning.mode:type_name -> service.pb.RemoteProvisioning.Mode
	3, // 4: service.pb.RemoteProvisioning.user_agent:type_name -> service.pb.UserAgent
	1, // 5: service.pb.GetConfigurationResponse.device_authentication_mode:type_name -> service.pb.GetConfigurationResponse.DeviceAuthenticationMode
	4, // 6: service.pb.GetConfigurationResponse.remote_provisioning:type_name -> service.pb.RemoteProvisioning
	5, // 7: service.pb.GetConfigurationResponse.build_info:type_name -> service.pb.BuildInfo
	6, // 8: service.pb.GetConfigurationResponse.ui:type_name -> service.pb.UIConfiguration
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_github_com_plgd_dev_client_application_pb_get_configuration_proto_init() }
func file_github_com_plgd_dev_client_application_pb_get_configuration_proto_init() {
	if File_github_com_plgd_dev_client_application_pb_get_configuration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserAgent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RemoteProvisioning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BuildInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UIConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetConfigurationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_plgd_dev_client_application_pb_get_configuration_proto_goTypes,
		DependencyIndexes: file_github_com_plgd_dev_client_application_pb_get_configuration_proto_depIdxs,
		EnumInfos:         file_github_com_plgd_dev_client_application_pb_get_configuration_proto_enumTypes,
		MessageInfos:      file_github_com_plgd_dev_client_application_pb_get_configuration_proto_msgTypes,
	}.Build()
	File_github_com_plgd_dev_client_application_pb_get_configuration_proto = out.File
	file_github_com_plgd_dev_client_application_pb_get_configuration_proto_rawDesc = nil
	file_github_com_plgd_dev_client_application_pb_get_configuration_proto_goTypes = nil
	file_github_com_plgd_dev_client_application_pb_get_configuration_proto_depIdxs = nil
}
