// ************************************************************************
// Copyright (C) 2022 plgd.dev, s.r.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: github.com/plgd-dev/client-application/pb/onboard_device.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnboardDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// endpoint in format <scheme>://<host>:<port>
	CoapGatewayAddress string `protobuf:"bytes,2,opt,name=coap_gateway_address,json=coapGatewayAddress,proto3" json:"coap_gateway_address,omitempty"`
	// authorization code from the hub
	AuthorizationCode string `protobuf:"bytes,3,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	// authorization provider from the hub
	AuthorizationProviderName string `protobuf:"bytes,4,opt,name=authorization_provider_name,json=authorizationProviderName,proto3" json:"authorization_provider_name,omitempty"`
	// hub id in uuid format to allow hub access to device
	HubId string `protobuf:"bytes,5,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	// list of hub certificate authorities in PEM format to verify the hub certificate
	CertificateAuthorities string `protobuf:"bytes,6,opt,name=certificate_authorities,json=certificateAuthorities,proto3" json:"certificate_authorities,omitempty"`
}

func (x *OnboardDeviceRequest) Reset() {
	*x = OnboardDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnboardDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardDeviceRequest) ProtoMessage() {}

func (x *OnboardDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardDeviceRequest.ProtoReflect.Descriptor instead.
func (*OnboardDeviceRequest) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescGZIP(), []int{0}
}

func (x *OnboardDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *OnboardDeviceRequest) GetCoapGatewayAddress() string {
	if x != nil {
		return x.CoapGatewayAddress
	}
	return ""
}

func (x *OnboardDeviceRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *OnboardDeviceRequest) GetAuthorizationProviderName() string {
	if x != nil {
		return x.AuthorizationProviderName
	}
	return ""
}

func (x *OnboardDeviceRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *OnboardDeviceRequest) GetCertificateAuthorities() string {
	if x != nil {
		return x.CertificateAuthorities
	}
	return ""
}

type OnboardDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnboardDeviceResponse) Reset() {
	*x = OnboardDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnboardDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardDeviceResponse) ProtoMessage() {}

func (x *OnboardDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardDeviceResponse.ProtoReflect.Descriptor instead.
func (*OnboardDeviceResponse) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescGZIP(), []int{1}
}

var File_github_com_plgd_dev_client_application_pb_onboard_device_proto protoreflect.FileDescriptor

var file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67,
	0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x22, 0xa4, 0x02, 0x0a,
	0x14, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x6f, 0x61, 0x70, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x63, 0x6f, 0x61, 0x70, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x11, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x3e, 0x0a, 0x1b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x68, 0x75, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x62, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x17, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x4f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67, 0x64, 0x2d,
	0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescOnce sync.Once
	file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescData = file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDesc
)

func file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescGZIP() []byte {
	file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescOnce.Do(func() {
		file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescData)
	})
	return file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDescData
}

var file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_plgd_dev_client_application_pb_onboard_device_proto_goTypes = []any{
	(*OnboardDeviceRequest)(nil),  // 0: service.pb.OnboardDeviceRequest
	(*OnboardDeviceResponse)(nil), // 1: service.pb.OnboardDeviceResponse
}
var file_github_com_plgd_dev_client_application_pb_onboard_device_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_plgd_dev_client_application_pb_onboard_device_proto_init() }
func file_github_com_plgd_dev_client_application_pb_onboard_device_proto_init() {
	if File_github_com_plgd_dev_client_application_pb_onboard_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OnboardDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OnboardDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_plgd_dev_client_application_pb_onboard_device_proto_goTypes,
		DependencyIndexes: file_github_com_plgd_dev_client_application_pb_onboard_device_proto_depIdxs,
		MessageInfos:      file_github_com_plgd_dev_client_application_pb_onboard_device_proto_msgTypes,
	}.Build()
	File_github_com_plgd_dev_client_application_pb_onboard_device_proto = out.File
	file_github_com_plgd_dev_client_application_pb_onboard_device_proto_rawDesc = nil
	file_github_com_plgd_dev_client_application_pb_onboard_device_proto_goTypes = nil
	file_github_com_plgd_dev_client_application_pb_onboard_device_proto_depIdxs = nil
}
