// ************************************************************************
// Copyright (C) 2022 plgd.dev, s.r.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ************************************************************************

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: github.com/plgd-dev/client-application/pb/own_device.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OwnDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Defines how long own process will wait for the OwnDeviceRequest with set_identity_certificate in nanoseconds. Default value is 15secs.
	Timeout int64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *OwnDeviceRequest) Reset() {
	*x = OwnDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnDeviceRequest) ProtoMessage() {}

func (x *OwnDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnDeviceRequest.ProtoReflect.Descriptor instead.
func (*OwnDeviceRequest) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescGZIP(), []int{0}
}

func (x *OwnDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *OwnDeviceRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type OwnDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filled when OwnDeviceRequest.get_identity_csr is true
	IdentityCertificateChallenge *IdentityCertificateChallenge `protobuf:"bytes,1,opt,name=identity_certificate_challenge,json=identityCertificateChallenge,proto3" json:"identity_certificate_challenge,omitempty"`
}

func (x *OwnDeviceResponse) Reset() {
	*x = OwnDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnDeviceResponse) ProtoMessage() {}

func (x *OwnDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnDeviceResponse.ProtoReflect.Descriptor instead.
func (*OwnDeviceResponse) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescGZIP(), []int{1}
}

func (x *OwnDeviceResponse) GetIdentityCertificateChallenge() *IdentityCertificateChallenge {
	if x != nil {
		return x.IdentityCertificateChallenge
	}
	return nil
}

type FinishOwnDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Use value form OwnDeviceResponse.get_identity_csr.state
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Certificate chain in PEM format
	Certificate []byte `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *FinishOwnDeviceRequest) Reset() {
	*x = FinishOwnDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishOwnDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishOwnDeviceRequest) ProtoMessage() {}

func (x *FinishOwnDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishOwnDeviceRequest.ProtoReflect.Descriptor instead.
func (*FinishOwnDeviceRequest) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescGZIP(), []int{2}
}

func (x *FinishOwnDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FinishOwnDeviceRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FinishOwnDeviceRequest) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type FinishOwnDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishOwnDeviceResponse) Reset() {
	*x = FinishOwnDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishOwnDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishOwnDeviceResponse) ProtoMessage() {}

func (x *FinishOwnDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishOwnDeviceResponse.ProtoReflect.Descriptor instead.
func (*FinishOwnDeviceResponse) Descriptor() ([]byte, []int) {
	return file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescGZIP(), []int{3}
}

var File_github_com_plgd_dev_client_application_pb_own_device_proto protoreflect.FileDescriptor

var file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67,
	0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x77, 0x6e, 0x5f,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x62, 0x1a, 0x13, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a,
	0x10, 0x4f, 0x77, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x11, 0x4f, 0x77, 0x6e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e,
	0x0a, 0x1e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x52, 0x1c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x6d,
	0x0a, 0x16, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4f, 0x77, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x19, 0x0a,
	0x17, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4f, 0x77, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x67, 0x64, 0x2d, 0x64, 0x65, 0x76, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescOnce sync.Once
	file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescData = file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDesc
)

func file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescGZIP() []byte {
	file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescOnce.Do(func() {
		file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescData)
	})
	return file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDescData
}

var file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_plgd_dev_client_application_pb_own_device_proto_goTypes = []interface{}{
	(*OwnDeviceRequest)(nil),             // 0: service.pb.OwnDeviceRequest
	(*OwnDeviceResponse)(nil),            // 1: service.pb.OwnDeviceResponse
	(*FinishOwnDeviceRequest)(nil),       // 2: service.pb.FinishOwnDeviceRequest
	(*FinishOwnDeviceResponse)(nil),      // 3: service.pb.FinishOwnDeviceResponse
	(*IdentityCertificateChallenge)(nil), // 4: service.pb.IdentityCertificateChallenge
}
var file_github_com_plgd_dev_client_application_pb_own_device_proto_depIdxs = []int32{
	4, // 0: service.pb.OwnDeviceResponse.identity_certificate_challenge:type_name -> service.pb.IdentityCertificateChallenge
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_plgd_dev_client_application_pb_own_device_proto_init() }
func file_github_com_plgd_dev_client_application_pb_own_device_proto_init() {
	if File_github_com_plgd_dev_client_application_pb_own_device_proto != nil {
		return
	}
	file_pb_initialize_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishOwnDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishOwnDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_plgd_dev_client_application_pb_own_device_proto_goTypes,
		DependencyIndexes: file_github_com_plgd_dev_client_application_pb_own_device_proto_depIdxs,
		MessageInfos:      file_github_com_plgd_dev_client_application_pb_own_device_proto_msgTypes,
	}.Build()
	File_github_com_plgd_dev_client_application_pb_own_device_proto = out.File
	file_github_com_plgd_dev_client_application_pb_own_device_proto_rawDesc = nil
	file_github_com_plgd_dev_client_application_pb_own_device_proto_goTypes = nil
	file_github_com_plgd_dev_client_application_pb_own_device_proto_depIdxs = nil
}
