# This is a basic workflow to help you get started with Actions

name: Build test binaries

# Controls when the action will run. Triggers the workflow push is only on main branch and PR on any branch.
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-binaries:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.20" # The Go version to download (if necessary) and use.

      - name: Set version and ui_file
        id: vars
        run: |
          git tag $(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
          echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          echo "ui_file=$(pwd)/.tmp/ui.tar.gz" >> $GITHUB_OUTPUT

      - name: Build client
        uses: goreleaser/goreleaser-action@v4
        with:
          # version of goreleaser which will be used
          version: latest
          args: release --rm-dist --skip-publish --skip-announce
        env:
          UI_SEPARATOR: "--------UI--------"
          UI_FILE: ${{ steps.vars.outputs.ui_file }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: client_application-${{ steps.vars.outputs.version }}
          path: |
            .tmp/dist/*.tar.gz
            .tmp/dist/*.zip
          retention-days: 7
