# Check that only correctly formatted golang code is merged
name: Check Format

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch branches and history so `git merge-base` in check-format-on-diff works correctly
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20" # The Go version to download (if necessary) and use.

      - name: Check formatting
        shell: bash
        run: tools/format/check-format-on-diff.sh --simplify --branch origin/${{ github.base_ref }}
