# Check that only correctly formatted golang code is merged
name: Check Format

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
        with:
          # fetch branches and history so `git merge-base` in check-format-on-diff works correctly
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22" # The Go version to download (if necessary) and use.
          check-latest: true

      - name: Check formatting
        shell: bash
        run: tools/format/check-format-on-diff.sh --simplify --branch origin/${{ github.base_ref }}
