name: Golangci-lint

# golangci-lint is a fast Go linters runner. It runs linters in parallel,
# uses caching, supports yaml config, has integrations with all major IDE and
# has dozens of linters included.
# see: https://github.com/golangci/golangci-lint-action

on:
  pull_request:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20" # The Go version to download (if necessary) and use.
      - run: go version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
