name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Install dependencies
      working-directory: ./web/playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./web/playwright
      run: npx playwright install --with-deps
    - name: Install dotenv
      run: npm install --save dotenv
    - name: Run Playwright tests
      working-directory: ./web/playwright
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./web/playwright/playwright-report/
        retention-days: 30
